### ISSUE TITLE
Is there a defined list of institutions available?

### ISSUE THREAD

**Issue by rowlandm** [RDA-DMP-Common/RDA-DMP-Common-Standard#10]
In the RDA webinar (https://youtu.be/-GrR8Yc4nJQ?t=2213) Tomasz mentioned the idea of this model being used to exchange information between systems.

The key here is having consistent metadata in those systems, with a simple example being the same list of defined instituations.

Is there a defined list of instituations available that is kept up to date that could be used by multple systems as a standard?

Apologies for this background question.

**Comment by rowlandm** [comment]
Actually I don't know where I saw an institution field,  maybe in the webinar. 

I couldn't find it in the schema

**Comment by TomMiksa** [comment]
I am not sure whether I understand your question. We do not have any list of institutions. You might have seen the institution field in the introduction of the webinar, when we were showing the motivation. During the model development, we found out that it is enough to use an identifier system that points unambiguously to a specific person. This can be ORCID, but also any other system. Having such an identifier is enough to retrieve additional information like the affiliation of a researcher. 
Hence, it turned out that there is no need to look for/create a list of institutions/universities. I am also afraid this would not be feasible and would have to be always somehow constrained.

**Comment by rowlandm** [comment]
Thanks goer the feedback @tommiska. You are right,  I can't figure out where that came from.  Apologies. 

Closing this.
