### ISSUE TITLE
Contributors have a "e-mail" attribute, and also an identifier alternative "mbox"

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/RDA-DMP-Common-Standard#17]
- There is an inconsistency between "e-mail" and "mbox"; if the semantics are different this should be explained.
- If the e-mail attribute is given it should not be necessary to repeat it as the identifier type?

**Comment by TomMiksa** [comment]
The idea is that we should be able to *contact* each contributor and precisly *identify* it. In the ideal case, the contributor has an email address and an identifier such as ORICD. 
However, we know that many people involved in data management are not necessairly researchers and there may be many internal identifier schemes used. Foro this reason we came up with a short vocabulary to distnguish between most common ones. We assumed that email/mbox is one of "identifiers". 

Since it leads to a confusion I think we can actually drop the email from the list of types. In case someone does not have a “proper” identifier, then they should set it to “other”.

**Comment by paulwalk** [comment]
Agreed.

I have removed `email` from the allowed value lists for the identifier type for both and `contributor` and `contact`.

Closing this issue now.
