### ISSUE TITLE
ContactPerson role for dmp.contributor is redundant with the dmp.contact in the model

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/RDA-DMP-Common-Standard#19]
The model has a exactly one contact, and zero or more contributors. However, the contributor.role can also be ContactPerson; this is redundant and inconsistent.

**Comment by TomMiksa** [comment]
We did this on purpose. We want always to have a contact person for a DMP, so that no DMP is an orphan. 
Contributor is to:
- list all people involved in managing data and writing the DMP
- be able to answer questions from DMPs like “who will be responsible for implementing this DMP”

**Comment by paulwalk** [comment]
There is a possibility of redundancy, due to the Datacite contributor types including a value of "ContactPerson", and this is unfortunate.

However, I would not like to throw away the recommendation to use the DataCite contributorTypes just because of this potential redundancy, and I agree with Tomasz that we definitely want the mandatory contact person property as well.

My recommendation: leave this as it is, and seek forgiveness later ;-)

**Comment by TomMiksa** [comment]
Isn't this contradictive with? https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/issues/16#issuecomment-558115485

I think the decision for now is to remove the references to DataCite.

**Comment by rwwh** [comment]
Removing the link to DataCite also solves this issue. Any replacement we insert for Contributor types should "avoid" contact-person roles.

**Comment by paulwalk** [comment]
Yes - the decision (based on the discussion in https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/issues/16#issuecomment-558115485) is to remove the connection to the DataCite 'roles'.
