### ISSUE TITLE
Dealing with "shared" dataset 

### ISSUE THREAD

**Issue by NZR** [RDA-DMP-Common/RDA-DMP-Common-Standard#2]
Let us consider the following situation where : 

DMP-1 --> DataSet-1
and
DMP-2 --> DataSet-1  (re-use)

This package of information should be transfered to another insitution. 
This can happen in 2 ways: 

- 1 single transaction containing 2 DMPs, and describing the dataset DataSet-1. 
  - in this case, the JSON format needs to be updated to allow for references to dataset rather than instance information (usage of an JSON internal reference can do the trick for import/export)
- 2 transaction, each containing 1 DMP, and the DataSet-1
  - in this case, we need a stable ID for the DataSet-1 so it does not get created twice on the receiver side. 
  - in this situation, one might decide to use a combination of available DOI's on the DataSet-1 as identifier. 

Which should be the prefered way ? Both are technically allowed by the current model.

**Comment by TomMiksa** [comment]
To keep things simple, I would go for the second option: every transaction contains only one DMP with datasets it describes. 
Each dataset has a dataset_id which is optional. When a DMP is in an early phase, there may be no identifier for data, e.g. no DOI. In a later phase, when DMP is complete, the ID very likely exists, because data has been published. Only when data has been published, it can be reused. This implies the dataset_id can be set.
