### ISSUE TITLE
Error in v1.0: dmp.language

### ISSUE THREAD

**Issue by hmpf** [RDA-DMP-Common/RDA-DMP-Common-Standard#20]
"ISO 6391-1" is probably a typo for "ISO 639-1". They are not **country**-codes but **language** codes.

**Comment by hmpf** [comment]
While it might not be very likely that a DMP will be written in Southern Sami (ISO 639-3 sma, no ISO 639-1 code), I don't understand why you default to ISO 639-1 in 2019. Not that ISO 639-3 doesn't have its detractors, but at least that one isn't limited to 676 different languages on a planet that still has an order of magnitude more than that.

**Comment by paulwalk** [comment]
Regarding:
> "ISO 6391-1" is probably a typo for "ISO 639-1". They are not country-codes but language codes.

Yes, and yes. Thanks for spotting these typos. I will fix these.

Regarding the preferred use of ISO 639-3:

I agree with you that we should use ISO 639-3. I have just recommended to my co-chairs that we change this now. Since the codes in  ISO 639-1 are a subset of the codes in  ISO 639-3, this change would be a "non-breaking" change to the recently published version of our application profile, so I believe that we can and should simply make this change immediately.

Thanks for reporting this!
