### ISSUE TITLE
Example "ex1-header-fundedProject.json" lacks a dataset

### ISSUE THREAD

**Issue by hmpf** [RDA-DMP-Common/RDA-DMP-Common-Standard#22]
According to the schema, all dmp's must have at least one dataset. Since a dataset have multiple obligatory (cardinality = 1) fields, an empty dataset does not validate according to the schema.

**Comment by TomMiksa** [comment]
Yes, that's true. This is because with each example we wanted to demonstrate something different and removed details that are not relevant. In this example, we want to show how to depict information in the maDMP that the project was funded. 

There is another example of a minimal DMP that shows which fields are obligatory to have a minimal DMP.
