### ISSUE TITLE
The "distribution"/"host" section is hard to understand

### ISSUE THREAD

**Issue by hmpf** [RDA-DMP-Common/RDA-DMP-Common-Standard#23]
The "host/distribution" section seems to conflate too many things. It seems to assume a non-distributed system that may only be located a single time in a single country (`geo_location`). The field is optional, so if a funder is looking at the dmp and asks: "is this dataset data stored multiple places", what's the correct answer? The definition of  both "host" and "distribution" is too vague. Is "host" a verb or a noun here?

There's no way to say "this dataset is in multiple datacenters in a single country, US east coast and US west coast". You can have multiple distributions, but what's the point if the only difference is the `geo_location` field?

**Comment by TomMiksa** [comment]
'Distribution' is defined in the same way as the W3C DCAT does it. It has nothing to do with distributed computing, or distributed storage. It's a way of saying that a given 'Dataset' has a specific instance available at a specific location, e.g. Interviews with patients are available as mp3s in Zenodo.

Since 'Distribution' focuses on the files, we had to add a concept that would describe some quality of service aspects of the place where the 'Distribution' is kept. For this reason we introduced the 'Host' class. In case the funder wants to find out whether "data is kept only in Europe", or "data has 3 backups", then all this information goes into 'Host'. 

Ad. "is this dataset data stored multiple places"
- you can define multiple distributions for a given dataset. For example, if your collection of interviews is available as mp3s on one server, and as wave files on the other
- the question you have asked can also be understood as "is data backed up". Then it's enough that you use Dataset-Distribution-Host connection and set approparite field in Host that backups are supported

Ad. "this dataset is in multiple datacenters in a single country, US east coast and US west coast"
For many areas there are no existing dictionaries that we could reuse. Hence, many of the fields are defined as Strings where you can put arbitrary values. To express what you want, you should use 'Host/backup_type' and write there that copies are distributed over the east and west coast. 
In case you're not talking here about copies, but let's say a federated database, this will still work. You define one Distribution that specifies the license, endpoint of the db to which one can connect, etc. In the Host you describe only the QoS aspects. 

I hope this answers all your questions.
