### ISSUE TITLE
grant_id should not be required

### ISSUE THREAD

**Issue by briri** [RDA-DMP-Common/RDA-DMP-Common-Standard#29]
The current schema indicates that grant_id is required but the statuses are: planned, applied, granted and rejected. 

It is unlikely that a grant_id would exist when the status is planned, applied or rejected.

**Comment by jomtov** [comment]
The grant_id is required only if you have a funding-entry (lines 886-975), as far as I discern. Having a funding entry in itself is not required, it is possible to validate perfectly without it. A dataset is a required key, though.

**Comment by hmpf** [comment]
This might be a matter of what an id is useful for. On one hand, it can be a PID (persistent, useful outside the place it was first defined). On the other, an id can be needed to make a repeated section uniquely referencable within the system, like a primary key in an SQL table. The latter need not be PIDs and need not be shared with anyone. Without something functioning like the latter, the only way to tell apart two datasets is the order they are defined in the json, so: dataset with index 0 vs. dataset with index 1 etc. (You could in fact use that index as an id and thus be explicit about it.)

I think the two uses has been conflated in this standard: you really need the latter type (since the standard does not define that arrays are ordered [though it may be assumed], but the first type can always be added *later*. This ties into #33 and #34.

**Comment by TomMiksa** [comment]
I think the cardinality of `grant_id` should be changed to 0..1. If I recall correctly, in the "project branch" of the specification we wanted to keep the options open.
