### ISSUE TITLE
Question: on the linking between metadata and DataSet

### ISSUE THREAD

**Issue by cmzwolf** [RDA-DMP-Common/RDA-DMP-Common-Standard#7]
In the actual model, Metadata is directly linked with Dataset. Or a dataset may have different distributions. Each distribution may have specific metadata. How could we express this fine grained metadata-distribution linking?

**Comment by TomMiksa** [comment]
Metadata component is used to answer questions like "Which metadata standard are you going to use to describe your data". The goal is not to provide the actual metadata on the dataset/distribution, but to point to a specific standard. For example, you would use metadata component to indicate that you will use ECHO Metadata Standard (ESDS-RFC-020) for data you captured. Then this data could be uploaded to different repositories in different file formats - to describe this you would use different distributions. These distributions will be deriving from the same dataset, and will be following the same metadata standard.

If your data is described different metadata standards, then in my opinion it makes more sense, to talk about two distnict datasets, rather than two distributions within the same dataset.
